[build-system]
requires = ["uv_build>=0.11.6,<0.12"]
build-backend = "uv_build"

[project]
name = "accuratum"
version = "0.1.0"
description = "A python library and CLI for creating Accuratum sundial diagrams"
readme = "README.md"
authors = [
    { name = "Paulo Eduardo de Brito", email = "pedebrito@unb.br" },
    { name = "Marco Aurélio A. Barbosa", email = "aureliobarbosa@gmail.com" }
]
maintainers = [
    { name = "Marco Aurélio A. Barbosa", email = "aureliobarbosa@gmail.com" }
]
license = "MIT"
license-files = ["LICENSE.md"]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Education",
]
keywords = [
    "astronomy",
    "education",
    "solar clock",
    "sundial",
]
dependencies = [
    "astropy>=7.1.0",
    "geopy>=2.4.1",
    "numpy>=2.2.6",
    "matplotlib>=3.10.3",
    "timezonefinder>=8.2.2",
    "tzdata>=2024.1",
    "astroplan>=0.10.1",
]

[project.optional-dependencies]
dev = [
    "ipykernel>=6.29.5",
    "pytest>=8.3.5",
    "pytest-mock>=3.14",
    "ruff>=0.11.11",
]

[project.scripts]
accuratum = "accuratum.cli:main"

[project.urls]
Homepage = "https://github.com/aureliobarbosa/accuratum"
Repository = "https://github.com/aureliobarbosa/accuratum"
Issues = "https://github.com/aureliobarbosa/accuratum/issues"

[tool.uv.build-backend]
module-root = ""

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--tb=short"

[tool.ruff]
target-version = "py311"
line-length = 120
extend-exclude = [
    "*.ipynb",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
