[project]
name = "accuratum"
version = "0.1.0"
description = "A python library for creating accuratum sundials"
readme = "README.md"
authors = [
    { name = "Paulo Eduardo de Brito", email = "pedebrito@unb.br" },
    { name = "Marco Aurélio A. Barbosa", email = "aureliobarbosa@gmail.com" }
]
maintainers = [
    { name = "Marco Aurélio A. Barbosa", email = "aureliobarbosa@gmail.com" }
]
license = "MIT"
license-files = ["LICENSE.md"]
requires-python = ">=3.11"
classifiers = [
    "Intended Audience :: Education",    
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Education",
]
keywords = [
    "astronomy",
    "education",
    "solar clock",
    "sundial",
]
dependencies = [
    "astropy>=7.1.0",
    "geopy>=2.4.1",
    "numpy>=2.2.6",
]

[project.optional-dependencies]
recommended = [
    "matplotlib>=3.10.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pytest>=8.3.5",
    "ruff>=0.11.11",
]

[project.urls]
repository = "https://github.com/aureliobarbosa/accuratum"
